# Generated by Django 4.0 on 2024-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='active_update_timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
