# Generated by Django 4.0 on 2024-02-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='aired',
        ),
        migrations.AddField(
            model_name='anime',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
