# Generated by Django 4.0 on 2024-02-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_aired_anime_end_date_anime_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
