# Generated by Django 4.0 on 2024-03-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='idx',
            field=models.IntegerField(blank=True, help_text='positional Ids for ML', null=True),
        ),
    ]
