# Generated by Django 4.0 on 2024-03-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='export',
            name='type',
            field=models.CharField(choices=[('ratings', 'Ratings'), ('anime', 'Anime')], default='ratings', max_length=20),
        ),
    ]
